version: '3.8'

services:
  localstack:
    image: localstack/localstack:latest
    environment:
      - AWS_DEFAULT_REGION=eu-west-2
      - SERVICES=s3, sqs
      - DEBUG=1
      - LS_LOG=trace
    ports:
      - "4566:4566"
      - "4510-4559:4510-4559"
    volumes:
      - "${TEMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - ./init_services:/etc/localstack/init/ready.d
